name: Deploy to Cloudflare

on:
  push:
  
jobs:
  deploy-sanity:
    name: Deploy Sanity Studio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies for Studio
        run: pnpm install --filter=studio --frozen-lockfile

      - name: Install Sanity CLI
        run: npm i -g @sanity/cli

      - name: Deploy Sanity
        run: |
          cd apps/studio
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" sanity deploy

  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies for Website
        run: pnpm install --filter=web --frozen-lockfile

      - name: Install Wrangler
        run: npm i -g wrangler

      - name: Build Website
        run: pnpm run build -- --filter=web

      - name: Deploy Website
        run: |
          cd apps/web
          CLOUDFLARE_API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}" wrangler pages publish --project-name fedeminaya ./public